version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql-events
    restart: always
    environment:
      MYSQL_DATABASE: eventsdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: bensaadmohamedamine/eventsproject:latest
    container_name: events-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eventsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data:
